### ISSUE TITLE
Include contribution amount?

### ISSUE THREAD

**Issue by dretax** [k0kubun/gitstar-ranking#27]
How about including the amount of contributions / year for users?

**Comment by k0kubun** [comment]
Tentatively in favor of adding it. But how do you feel if the top of ranking is concurred by bots or users having a repository which is automatically committed every day?

**Comment by k0kubun** [comment]
As my maintenance resource is limited, temporarily close this feature request. Sorry.

**Comment by dretax** [comment]
Meh, fine.
