### ISSUE TITLE
unable to update stars button

### ISSUE THREAD

**Issue by afc163** [k0kubun/gitstar-ranking#39]
https://gitstar-ranking.com/ant-design is still failed, after signing up in GitHub.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/507615/36027637-15a4a2d4-0dd7-11e8-8f87-a1c44251613b.png">

**Comment by k0kubun** [comment]
Are you a member of ant-design organization? Currently you can't update an organization which you are not in.

**Comment by k0kubun** [comment]
Hmm, but there is no reason to restrict it to update it using your token. I'll support it.

**Comment by afc163** [comment]
I am a member of ant-design organization, actually, the owner.

**Comment by k0kubun** [comment]
Sorry about that.

Now I allowed to update organization by everyone. And I actually updated your organization like this https://gitstar-ranking.com/ant-design. Great number of stars :+1:
