### ISSUE TITLE
Update Readme screenshot

### ISSUE THREAD

**Issue by AdityaSrivast** [k0kubun/gitstar-ranking#50]
Great implementation @k0kubun . I assume that earlier it was named github-ranking. But now it has been renamed to gitstar-ranking. However, I found that the screenshot on readme to be still that of the previous website.
![image](https://user-images.githubusercontent.com/31389740/56342480-c30f5100-61d5-11e9-8250-d13c06ab311d.png)
Probably we should update it. Thanks.

**Comment by k0kubun** [comment]
done, thanks
