### ISSUE TITLE
nodejs org is missing

### ISSUE THREAD

**Issue by styfle** [k0kubun/gitstar-ranking#56]
## Actual

https://gitstar-ranking.com/organizations

https://gitstar-ranking.com/nodejs

## Expected

https://github.com/nodejs

**Comment by styfle** [comment]
Looks like it was just updated via @quietshu 🎉 

```
mutation {
  updateUser(login: "nodejs") {
    payload
  }
}
```

**Comment by k0kubun** [comment]
Thanks!

Some years ago GitHub restricted gitstar-ranking's original usage of API calls, so unfortunately adding new users are organizations are done in a passive manner now. 
Maybe we could add a button to ask users to fetch new users sometimes, but right now adding a new user is triggered only when a login user finds a missing user page.

**Comment by styfle** [comment]
> Maybe we could add a button to ask users to fetch new users sometimes

That would be great 👍
