### ISSUE TITLE
[Bug] Failed to update the amount of stars

### ISSUE THREAD

**Issue by Berkeley-Reject** [k0kubun/gitstar-ranking#60]
**How to reproduce**
1. Login with GitHub account
2. Navigate to a user's profile (example: [Berkeley-Reject](https://gitstar-ranking.com/Berkeley-Reject))
3. Click on the "Update Stars" button
4. The title of the button changes to "Updating Stars.."
5. After waiting for a few minutes, the amount of stars doesn't change

**Comment by k0kubun** [comment]
You're right. For some reason the worker was stuck and it was fixed by restarting it. Now I believe your job is also consumed it's up to date.

**Comment by Berkeley-Reject** [comment]
> You're right. For some reason the worker was stuck and it was fixed by restarting it. Now I believe your job was also consumed and it's up to date.

Thanks, it now works well.
