### ISSUE TITLE
Updating star do not work since last week

### ISSUE THREAD

**Issue by KunMinX** [k0kubun/gitstar-ranking#61]
The star count of my 'Jetpack MVVM Best Practice' project has 4000+ now ,
but updating star do not work since last week ,
could you help me ?

https://gitstar-ranking.com/KunMinX

**Comment by k0kubun** [comment]
Sorry for the trouble. You're right, the workers were stuck... I'm still investigating the reason, but in the meantime workers are running after a restart.

**Comment by KunMinX** [comment]
@k0kubun 
Thanks for your information.
