### ISSUE TITLE
Stars are not updating for org profile

### ISSUE THREAD

**Issue by tejas-ardeshna** [k0kubun/gitstar-ranking#70]
Hi I was checking org page but I found that stars are not updating in page:

https://gitstar-ranking.com/simformsolutionspvtltd

It's showing the last fetch on 2017/09/05 16:43. 

Kindly update

**Comment by k0kubun** [comment]
Because of the past GitHub API policy changes, it's been impossible to keep everything up to date. For such accounts, you can login and fix it by yourself. I did it for this account now.
