### ISSUE TITLE
JSON API for extracting the data shown

### ISSUE THREAD

**Issue by C0DK** [k0kubun/gitstar-ranking#72]
I am trying to datamine the biggest repositories and would love to use your tool to get that data, however i have to scrape it currently, which is less than ideal.

**Comment by k0kubun** [comment]
Unfortunately I'm not paying a lot of money to run the infrastructure of this service for data mining, so I recommend you to use this project instead https://github.blog/2017-01-19-github-data-ready-for-you-to-explore-with-bigquery/.
