### ISSUE TITLE
Per-city ranking

### ISSUE THREAD

**Issue by muety** [k0kubun/gitstar-ranking#75]
Great project, thanks a lot! I have the following feature request.

Similar to what [vdaubry/github-awards](https://github.comvdaubry/github-awards) does, it would be cool to have a ranking grouped by cities, languages and / or both.

**Comment by k0kubun** [comment]
It's feasible, but the largest concern right now is the small free storage space of the database. Would you be interested in funding me through https://github.com/sponsors/k0kubun for accommodating these rankings?

**Comment by muety** [comment]
I'm thinking about it 🤓

**Comment by k0kubun** [comment]
OK, please reopen this when you're actually interested. Thanks.

**Comment by muety** [comment]
I AM interested, otherwise I wouldn't have made this feature request 😅.

**Comment by k0kubun** [comment]
I meant interested in fixing the storage cost problem, which is blocking the feature. Until it's funded by somebody who is interested in the feature, I cannot implement the feature anyway.

**Comment by Hexstream** [comment]
Do you have a ballpark cost estimate? Storage is pretty cheap these days.

Right now I would say [git-awards](http://git-awards.com/) is a much better project, except the extended lack of updates (very stale data) pretty much effectively makes it useless, which gives you a nice opportunity to take over the market.

**Comment by k0kubun** [comment]
In the cloud service I'm using, it seems to cost $6/mo to upgrade the storage size.

> Right now I would say [git-awards](http://git-awards.com/) is a much better project, except the extended lack of updates (very stale data) pretty much effectively makes it useless, which gives you a nice opportunity to take over the market.

In the past, GitHub banned this service for the number of API calls which were made by the service, and thus I changed the strategy to update information as instructed. It's simply impossible for any service to make every data up to date unless the service is officially offered by GitHub. I only maintain what's possible by GitHub's policies. If you really need a service that has up-to-date information, you have to ask GitHub to build one.

**Comment by Hexstream** [comment]
It's probably fine if you can only update profile data on request, but git-awards seemingly doesn't support even that anymore.

**Comment by Hexstream** [comment]
> In the past, GitHub banned this service for the number of API calls which were made by the service, and thus I changed the strategy to update information as instructed.

I bet you can probably manage to throttle automated requests enough that it would be allowed? The site would still be useful even if most profiles had month-old data, and you could update immediately upon request from an account holder...

**Comment by k0kubun** [comment]
> I bet you can probably manage to throttle automated requests enough that it would be allowed?

By the terms of service, you're allowed to use API tokens only for purposes which users specifically asked you to use for. So I can use only my API key to update data of random users. Even if we put a button that allows this service to update any user, I don't think the number of API tokens would reach the point where we can maintain meaningful amount of users up to date anyway. Please stop pushing me for something which you're not allowed to build.

**Comment by Hexstream** [comment]
Ok, that's too bad because I really loved the concept of git-awards.

**Comment by k0kubun** [comment]
If you love git-awards so much, first of all you came to a wrong repository :)

**Comment by Hexstream** [comment]
Since git-awards stopped updating, and you're still updating, I hoped you could implement the git-awards features I love, but it seems the reason they stopped updating and you didn't implement those features are the same after all...
