### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by muety** [k0kubun/gitstar-ranking#76]
Another funny feature would be to have badges (like [shields.io](https://shields.io)) to embed in your README or some online forum 🤓.

**Comment by k0kubun** [comment]
Would you like to put that on your README.md? If so, could you try building a badge you want using `https://img.shields.io/badge/<LABEL>-<MESSAGE>-<COLOR>`? 

Then I can build an endpoint which returns the same SVG but dynamically changes based on total stars, for example.

**Comment by muety** [comment]
Essentially, it would even be sufficient to have an endpoint that returns data in the format [specified here](https://shields.io/endpoint). For instance:

```json
{
  "schemaVersion": 1,
  "label": "git rank",
  "message": "1024"
}
```

**Comment by k0kubun** [comment]
Cool. Could you try this out?

![](https://img.shields.io/endpoint?url=https%3A%2F%2Fgitstar-ranking.com%2Fusers%2Fmuety%2Fshields)
