### ISSUE TITLE
Expand charts to top 5000?

### ISSUE THREAD

**Issue by davidjbradshaw** [k0kubun/gitstar-ranking#77]
Given the size of the GitHub user base, would it be possible to expand the list of the top 1,000 accounts/orgs/projects to a higher value, say 2,500 or 5,000?

**Comment by k0kubun** [comment]
Sure, done.

Yesterday I migrated the database from MySQL to PostgreSQL and I failed to migrate some of the data. Then I started to scan all users using my API key, so it might take some time to make them up to date.
