### ISSUE TITLE
Auth via github is broken for me

### ISSUE THREAD

**Issue by lgg** [k0kubun/gitstar-ranking#80]
![image](https://user-images.githubusercontent.com/12018713/113025494-b00ea500-9190-11eb-8ec3-0a0d778a21bf.png)

![image](https://user-images.githubusercontent.com/12018713/113025551-bd2b9400-9190-11eb-9587-7812ee61cdb1.png)

Also my username is seems to be broken: https://gitstar-ranking.com/lgg

**Comment by k0kubun** [comment]
Deployed a version which fixed the bug. Please try it when you have a chance.

**Comment by lgg** [comment]
@k0kubun thank you! Everything work fine now. Thank you for creating a great project, it's awesome!
