### ISSUE TITLE
Ask how to get repos with the highest count of stars

### ISSUE THREAD

**Issue by AndyLuo1029** [k0kubun/gitstar-ranking#89]
Hi k0kubun!

Sorry to disrupt you. I'm currently doing a research about top starred repos on GitHub. However, I found it's hard to get top 10k repos (ranked by stars) via original GitHub REST API since the REST API only return top 1k repos. And if I use query like `star:<xxx`, the result is incorrect.(You can check [this link](https://github.com/search?utf8=%E2%9C%93&q=stars%3A%3C1000000&type=repositories), it searched repos with less than 1 million stars and order them by stars desc, but the first repo in return list only have 900+ stars. It's obviously incorrect since we all know the top repos have more than 300k stars on GitHub.)

I've noticed that your website has top 50k repos ranked by stars, which is better than REST API can provide. So I'm curious with how you get these repos? Do you crawl all the repos on GitHub and store them in database, then you rank them? Or you have some amazing query methods that can get these repos with correct stars in real-time?

I tried to read your code but I'm totally rookie to Ruby. It will be very appreciated if you can give me some kind hints with how to get the data that I want.

Best wishes,
Andy

**Comment by k0kubun** [comment]
> Do you crawl all the repos on GitHub and store them in database, then you rank them?

This. When this website was built 9 years ago, they didn't care about how many concurrent requests a single consumer credential is querying REST API. So we just have 100 API tokens concurrently querying the API.

Some years later, they contacted us and said we should no longer be doing this. So it's crawling API with only a single API token. It's much more slower today, so this method doesn't really work for you.

I advise you to query https://www.gharchive.org/ instead.
